const pageConfig = {
    storageKey: "wordMasteryProgress",
    functionsList: [
        { id: "copypaste", name: "1. Copier/Coller" },
        { id: "undoredo", name: "2. Annuler/Rétablir" },
        { id: "save", name: "3. Enregistrer" },
        { id: "formatting", name: "4. Formatage" },
        { id: "selectall", name: "5. Tout Sélectionner" },
        { id: "find", name: "6. Rechercher" },
        { id: "print", name: "7. Imprimer" },
        { id: "fileops", name: "8. Fichiers" },
        { id: "fontsize", name: "9. Taille Police" },
        { id: "hyperlink", name: "10. Lien" },
        { id: "align", name: "11. Alignement" },
        { id: "styles", name: "12. Styles" },
        { id: "navpane", name: "13. Navigation" },
        { id: "trackchanges", name: "14. Suivi" },
        { id: "templates", name: "15. Modèles" },
        { id: "clipboard", name: "16. Presse-papiers" },
        { id: "dictation", name: "17. Dictée" },
        { id: "readmode", name: "18. Mode Lecture" },
        { id: "smartlookup", name: "19. Recherche Intel." },
        { id: "visuals", name: "20. Visuels" },
    ],
};
