const pageConfig = {
    storageKey: "excelMasteryProgress",
    functionsList: [
        { id: "sum", name: "1. SOMME" },
        { id: "average", name: "2. MOYENNE" },
        { id: "if", name: "3. SI" },
        { id: "vlookup", name: "4. RECHERCHEV" },
        { id: "countif", name: "5. NB.SI" },
        { id: "sumif", name: "6. SOMME.SI" },
        { id: "xlookup", name: "7. RECHERCHEX" },
        { id: "max", name: "8. MAX" },
        { id: "min", name: "9. MIN" },
        { id: "count", name: "10. NB" },
        { id: "counta", name: "11. NBVAL" },
        { id: "and", name: "12. ET" },
        { id: "or", name: "13. OU" },
        { id: "concat", name: "14. CONCAT" },
        { id: "left", name: "15. GAUCHE" },
        { id: "right", name: "16. DROITE" },
        { id: "mid", name: "17. STXT" },
        { id: "today", name: "18. AUJOURDHUI" },
        { id: "iferror", name: "19. SIERREUR" },
        { id: "indexmatch", name: "20. INDEX+EQUIV" },
    ],
};
