const pageConfig = {
    storageKey: "powerpointMasteryProgress",
    functionsList: [
        { id: "morph", name: "1. Morphose" },
        { id: "designer", name: "2. Designer" },
        { id: "newslide", name: "3. Nouvelle Diapo" },
        { id: "duplicate", name: "4. Dupliquer" },
        { id: "startshow", name: "5. Démarrer" },
        { id: "blackwhite", name: "6. Écran N/B" },
        { id: "group", name: "7. Grouper" },
        { id: "align", name: "8. Alignement" },
        { id: "fontsize", name: "9. Taille Police" },
        { id: "formatting", name: "10. Formatage" },
        { id: "copyformat", name: "11. Copier Format" },
        { id: "selectall", name: "12. Tout Sélect." },
        { id: "save", name: "13. Enregistrer" },
        { id: "undoredo", name: "14. Annuler/Rétab." },
        { id: "pointer", name: "15. Pointeur" },
        { id: "presenter", name: "16. Présentateur" },
        { id: "quickstarter", name: "17. QuickStarter" },
        { id: "zoom", name: "18. Zoom" },
        { id: "collab", name: "19. Collaboration" },
        { id: "smartart", name: "20. SmartArt" },
    ],
};
